<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Webpatser\Uuid\Uuid;

class Tenant extends Model
{
  protected $fillable = ['name', 'uuid', 'token'];

  protected $casts = [
    'active' => 'boolean'
  ];

  public static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub

    self::creating(function ($model) {
      $model->uuid = (string) Uuid::generate(4);
    });
  }

  public function users()
  {
    return $this->hasMany(User::class);
  }

  // Accesors
  public function getUrlTokenAttribute()
  {
    return route('site.menu.show', ['token' => $this->token]);
  }
}
